### ISSUE TITLE
Does this work on IOS, I am having trouble integrating, any specific prerequisites?

### ISSUE THREAD

**Issue by vmwsree** [dynamitechetan/razorpay_flutter#1]

**Comment by dynamitechetan** [comment]
Yes it works on ios. I've tried it. What problem you are getting?

**Comment by dynamitechetan** [comment]
Screenshot from iPhone X
![image](https://user-images.githubusercontent.com/14369357/50377681-a14af680-0647-11e9-8fa7-0550fdef4637.png)

**Comment by dynamitechetan** [comment]
No. Please update your XCode version.

**Comment by vmwsree** [comment]
i  saw u importing SwiftRazorpayPlugin swift file but i am getting a file not found error,
what is the right way to do it , or how to import swift file in objective c

**Comment by vmwsree** [comment]
[!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pod being used is: razorpay_plugin


Is this step required? because when i add the use_framework! line I get


error: Multiple commands produce '/Users/vivekmohan/Work/flutter/projects/flutter-mobile/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Razorpay.framework':

**Comment by vmwsree** [comment]
`  error: Multiple commands produce '/Users/vivekmohan/Work/flutter/projects/flutter-mobile/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Razorpay.framework':
    1) Target 'Runner' has copy command from '/Users/vivekmohan/Work/flutter/projects/flutter-mobile/ios/Razorpay.framework' to '/Users/vivekmohan/Work/flutter/projects/flutter-mobile/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Razorpay.framework'
    2) That command depends on command in Target 'Runner': script phase “[CP] Embed Pods Frameworks”
    error: Multiple commands produce '/Users/vivekmohan/Work/flutter/projects/flutter-mobile/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework':
    1) Target 'Runner' has copy command from '/Users/vivekmohan/Work/flutter/projects/flutter-mobile/ios/Flutter/Flutter.framework' to '/Users/vivekmohan/Work/flutter/projects/flutter-mobile/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework'
    2) That command depends on command in Target 'Runner': script phase “[CP] Embed Pods Frameworks”
    warning: Capabilities for Runner may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the build settings editor. (in target 'Runner')
    warning: ignoring duplicated output file: '/Users/vivekmohan/Work/flutter/projects/flutter-mobile/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework' (in target 'Runner')
    warning: ignoring duplicated output file: '/Users/vivekmohan/Work/flutter/projects/flutter-mobile/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Razorpay.framework' (in target 'Runner')
    note: Using new build systemnote: Planning buildnote: Constructing build description
Could not build the application for the simulator.
Error launching application on iPhone XR.`

complete error

**Comment by dynamitechetan** [comment]
Add "use_frameworks!" to your Podfile.
https://stackoverflow.com/questions/29091522/error-running-pod-install-with-swift

**Comment by vmwsree** [comment]
=== BUILD TARGET url_launcher OF PROJECT Pods WITH CONFIGURATION Debug ===
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/razorpay_plugin-umbrella.h"
            ^
    /Users/vivekmohan/Work/flutter/projects/flutter-mobile/ios/Pods/Target Support Files/razorpay_plugin/razorpay_plugin-umbrella.h:13:9: error: include of non-modular header inside framework module 'razorpay_plugin': '/Users/vivekmohan/Work/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_plugin-0.0.3/ios/Classes/RazorpayPlugin.h'
    #import "RazorpayPlugin.h"
            ^
    <unknown>:0: error: could not build Objective-C module 'razorpay_plugin'
Could not build the application for the simulator.
Error launching application on iPhone XR.

this is the latest error

can you paste ur flutter doctor -v

**Comment by vmwsree** [comment]
@dynamitechetan please share your 
flutter doctor -v

**Comment by vmwsree** [comment]
Hi issue is solved thanks to
https://github.com/flutter/flutter/issues/16049

**Comment by kbrmimbyl** [comment]
Hi, I have ```use_frameworks!``` in my pod file but it crashes on iOS. When I try to launch the Razorpay payment screen, it says the following (repeat 4-5 times) and the app crashes:

```
 "signalStrengthChanged:info:",
    "cellChanged:cell:",
    "connectionStateChanged:connection:dataConnectionStatusInfo:",
    "carrierBundleChange:"
)```

However, it works fine on Android.

Is there anything else I need to do?
