### ISSUE TITLE
Kindly update razor pay official pod plugin to 1.1.0 and your plugin to support Swift 5.0

### ISSUE THREAD

**Issue by bittu-dvlpr** [dynamitechetan/razorpay_flutter#13]

**Comment by mohansiriga7** [comment]
@dynamitechetan Can you please update your plugin to support Swift 5.0. This plugin is working really fine with android but the IOS build is unable to get build successfully in XCode.

**Comment by sharad-paghadal** [comment]
I'm having the same issue with Swift 5. Please update your plug in to support it @dynamitechetan

**Comment by rajeevjaiswal** [comment]
@dynamitechetan It really needs to be updated . Please look into this issue

**Comment by dynamitechetan** [comment]
Okay.. I'll work on this now.

**Comment by sharad-paghadal** [comment]
@dynamitechetan If you have too much work load, I can do this if you provide some guidance.

**Comment by dynamitechetan** [comment]
hi @sharad-paghadal I think its not a big issue. Just need to update the pod version to 1.1.2 which is  Compiled in Swift version 5. I'll fix it. Thanks for helping.

**Comment by dynamitechetan** [comment]
Hi @rajeevjaiswal @mohansiriga7 @bittu-dvlpr I've update the plugin version after merging @sharad-paghadal changes. 
Can you please try using ` 0.2.9` version and see if it is working with swift5. razorpay pod version is also updated to 1.1.2

**Comment by raveesh-me** [comment]
App crashes on 0.2.9 android even before a full launch on android. I've opened a new issue
