### ISSUE TITLE
Plugin is missing a feature to add notes, similarly to "prefill".

### ISSUE THREAD

**Issue by ukdhuri** [dynamitechetan/razorpay_flutter#2]
Plugin is missing a feature to add notes, similarly to "prefill".

Please refer documentation below.
https://docs.razorpay.com/docs/notes

**Comment by dynamitechetan** [comment]
I added notes in Android module. I am not able to find any docs on how to add it in ios.

**Comment by sharad-paghadal** [comment]
@ukdhuri 
this is achieved as @dynamitechetan accepted my pull request. Please close this issue as it's fixed.

**Comment by dynamitechetan** [comment]
Thanks @sharad-paghadal
