### ISSUE TITLE
Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler

### ISSUE THREAD

**Issue by pobyt** [dynamitechetan/razorpay_flutter#26]
iOS build is failing with below exception with new XCODE release Version 11.0.
Please update your iOS SDK to 5.1 in Flutter Project.
Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: /ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64.swiftmodule

**Comment by yashdabi** [comment]
Same issue arriving for me...**Please Help**
I am not able to build my project because of this
