### ISSUE TITLE
android.permission.RECEIVE_SMS error while uploading to playstore

### ISSUE THREAD

**Issue by rajeshzmoke** [dynamitechetan/razorpay_flutter#5]
I see that razorpay_flutter uses 
> android.permission.RECEIVE_SMS

but my application does not use this permission, when i tried to upload a build to play store i got a missing `android.permission.RECEIVE_SMS` warning
after adding it to my androidmanifest the warning went away, so it is not clear in the readme, so

Update the readme to include 
`    <uses-permission android:name="android.permission.RECEIVE_SMS" />
`

**Comment by vmwsree** [comment]
But  the new razorpay sdk should not use sms right

**Comment by dynamitechetan** [comment]
Fixed.
