### ISSUE TITLE
Plugin is crashing on Android X

### ISSUE THREAD

**Issue by kaumudpa** [dynamitechetan/razorpay_flutter#7]
Plugin is crashing on android X

**Comment by dynamitechetan** [comment]
any logs?

**Comment by kaumudpa** [comment]
Nopes, This plugin was working perfectly fine, we moved our project to AndroidX and this plugin as well, since then it started crashing.

**Comment by MDSADABWASIM** [comment]
Please update plugin with Android X support

**Comment by dynamitechetan** [comment]
@MDSADABWASIM @kaumudpa fixed 🎉

**Comment by kbrmimbyl** [comment]
Thanks for fixing @dynamitechetan. Starting which version does this plugin have AndroidX support?
